SECTIONS = {
    'unity.scopes.Category': 'Filtering',
    'unity.scopes.CategoryRenderer': 'Filtering',
    'unity.scopes.ColumnLayout': 'Filtering',
    'unity.scopes.Department': 'Filtering',
    'unity.scopes.FilterBase': 'Filtering',
    'unity.scopes.FilterOption': 'Filtering',
    'unity.scopes.FilterState': 'Filtering',
    'unity.scopes.OptionSelectorFilter': 'Filtering',

    'unity.scopes.testing': 'Testing',
    'unity.scopes.testing.AndersonDarlingTest': 'Testing',
    'unity.scopes.testing.Benchmark': 'Testing',
    'unity.scopes.testing.Benchmark.Result': 'Testing',
    'unity.scopes.testing.StudentsTTest': 'Testing',

    'unity.scopes.ConfigException': 'Exceptions',
    'unity.scopes.MiddlewareException': 'Exceptions',
    'unity.scopes.NotFoundException': 'Exceptions',
    'unity.scopes.ObjectNotExistException': 'Exceptions',
    'unity.scopes.TimeoutException': 'Exceptions',

    'unity.scopes.ActionMetadata': 'Previews',
    'unity.scopes.PreviewListenerBase': 'Previews',
    'unity.scopes.PreviewQueryBase': 'Previews',
    'unity.scopes.PreviewReply': 'Previews',
    'unity.scopes.PreviewWidget': 'Previews',

    'unity.scopes.ActivationListenerBase': 'Searching',
    'unity.scopes.ActivationQueryBase': 'Searching',
    'unity.scopes.ActivationResponse': 'Searching',
    'unity.scopes.Annotation': 'Searching',
    'unity.scopes.CannedQuery': 'Searching',
    'unity.scopes.CategorisedResult': 'Searching',
    'unity.scopes.ListenerBase': 'Searching',
    'unity.scopes.QueryBase': 'Searching',
    'unity.scopes.QueryCtrl': 'Searching',
    'unity.scopes.QueryMetadata': 'Searching',
    'unity.scopes.Registry': 'Searching',
    'unity.scopes.Reply': 'Searching',
    'unity.scopes.Result': 'Searching',
    'unity.scopes.Runtime': 'Searching',
    'unity.scopes.Scope': 'Searching',
    'unity.scopes.ScopeBase': 'Searching',
    'unity.scopes.ScopeMetadata': 'Searching',
    'unity.scopes.SearchListenerBase': 'Searching',
    'unity.scopes.SearchMetadata': 'Searching',
    'unity.scopes.SearchQueryBase': 'Searching',
    'unity.scopes.SearchReply': 'Searching',

    'unity.scopes.Link': 'Common',
    'unity.scopes.ObjectProxy': 'Common',
    'unity.scopes.Variant': 'Common',
    'unity.scopes.VariantBuilder': 'Common',

    'unity.scopes.OnlineAccountClient': 'Platform Services',
    
    'tutorial': 'Searching',
    '*': 'Searching',
}
